spring.application.name=demo
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.mode=always
spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
jwt.secret=testSecretKeyForJWTGenerationMustBeLongEnoughForSecureHS512Signing1234567890
jwt.expiration=3600000